# filepath: .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3️⃣ Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # 4️⃣ Install all dependencies including dev tools
      - name: Install dependencies
        run: poetry install --with dev

      # 5️⃣ Run code format and lint checks
      - name: Run Black
        run: poetry run black --check .

      - name: Run Flake8
        run: poetry run flake8

      - name: Run isort
        run: poetry run isort --check-only .

      # 6️⃣ Run tests
      - name: Run Tests
        run: poetry run pytest